name: Languages Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  languages-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Languages Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html,css
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_indepth: yes
      - name: Commit SVG to repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add metrics.plugin.languages.svg
          git commit -m "Add Languages Metrics SVG"
          git push
